DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS TRAINER;
DROP TABLE IF EXISTS PHYSIOTHERAPIST;
DROP TABLE IF EXISTS APPOINTMENT;

CREATE TABLE USER(
USER_ID INT NOT NULL,
USERNAME VARCHAR(255),
DOB DATE,
MOBNUMBER INT,
EMAIL VARCHAR(30),
ADDRESS VARCHAR(255),
PRIMARY KEY(USER_ID)
);

CREATE TABLE TRAINER (
TRAINER_ID INT NOT NULL PRIMARY KEY,
TRAINER_GENDER CHAR(1),
TRAINER_NAME VARCHAR(255)
);

CREATE TABLE PHYSIOTHERAPIST (
PHYSIO_ID INT NOT NULL PRIMARY KEY,
PHYSIO_NAME VARCHAR(255)
);

CREATE TABLE APPOINTMENT(
APPOINTMENT_ID INT NOT NULL PRIMARY KEY,
USER_ID INT,
PACKAGE VARCHAR(255),
APPOINTMENT_DATE DATE,
PHYSIO_REQUIRED CHAR(1),
TRAINER_ID INT NOT NULL,
PHYSIO_ID INT NOT NULL,
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
FOREIGN KEY (TRAINER_ID) REFERENCES TRAINER(TRAINER_ID),
FOREIGN KEY (PHYSIO_ID) REFERENCES PHYSIOTHERAPIST(PHYSIO_ID)
);